import {
  CampaignFormStep,
  BrandLocation,
  Gender,
  Objective,
  SocialMedia,
} from 'models';

export const brandFormSteps = [
  CampaignFormStep.One,
  CampaignFormStep.Two,
  CampaignFormStep.Three,
  CampaignFormStep.Four,
];

// Step 1
export const campaignObjs = [
  {
    value: Objective.Conversations,
    desc: 'Just testing',
    id: '1',
  },
  {
    value: Objective.Awareness,
    desc: 'Just testing1',
    id: '2',
  },
  {
    value: Objective.Contents,
    desc: 'Just testing3',
    id: '3',
  },
];

export const platforms = [
  {
    id: '1',
    value: SocialMedia.Instagram,
  },
  {
    id: '2',
    value: SocialMedia.TikTok,
  },
  {
    id: '3',
    value: SocialMedia.Facebook,
  },
  {
    id: '4',
    value: SocialMedia.Twitter,
  },
];

export const campaignTypes = [
  {
    id: 1,
    value: 'Challenges + Creator Licensing',
    desc: 'The top performing contents generated by creators who joined your open challenge campaign can also be used in paid creator ads.',
  },
  {
    id: 2,
    value: 'Organic Posts + Creator Licensing',
    desc: 'Creators will generate content to post organically on their Instagram feed and/or TikTok feed. You can also use this content in paid creator ads.',
  },
  {
    id: 3,
    value: 'UGC + Creator Licensing',
    desc: 'Creators will generate content that you can use in paid creator ads and on other digital channels like your website.',
  },
  {
    id: 4,
    value: 'Organic Posts',
    desc: 'Creators will generate content to post organically on their Instagram and/or TikTok feed.',
  },
  {
    id: 5,
    value: 'Challenges',
    desc: 'Creators will generate content by participating in your challenge and posting them organically on their Instagram and/or TikTok feed.',
  },
];

export const campaignBudgets = [3000, 5000, 10000];

// Step 2
export const locations: { name: BrandLocation; text: string; id: string }[] = [
  { id: '1', name: 'Africa', text: 'Africa' },
  { id: '2', name: 'NGR', text: 'NGR only' },
];

export const genders: Gender[] = ['any', 'male', 'female'];
